# General configuration file for ms-annotator
# NOTE: paths relative to root directory of project

# Location to read in input taxon ids
taxon_file: taxon_query.csv

# Place to save annotated data
data_dir: data
#
# Known assemblies table
known_assemblies: data/known_asseblies.csv

# NCBI assemblies, will be saved in data_dir
ncbi_assemblies_url: ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/archaea/assembly_summary.txt

